version: '3.4'

services:
  identitydb:
    container_name: identitydb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=IdentityDb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  chatdb:
    container_name: chatdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  folks.apigateway:
    container_name: folks.apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AuthenticationOptions__Authority=http://192.168.0.104:8001"
    depends_on:
      - folks.identityservice.api
      - folks.chatservice.api
    ports:
      - "8000:80"

  folks.chatservice.api:
    container_name: folks.chatservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AuthenticationOptions__Authority=http://192.168.0.104:8001"
      - "MongoDbConfig__ConnectionString=mongodb://chatdb:27017"
      - "MongoDbConfig__DatabaseName=ChatDb"
    depends_on:
      - chatdb
      - rabbitmq

  folks.identityservice.api:
    container_name: folks.identityservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__PostgreSqlConnectionString=Server=identitydb;Port=5432;Database=IdentityDb;User Id=admin;Password=admin1234;"
    depends_on:
      - identitydb
      - rabbitmq
    ports:
      - "8001:80"
