version: '3.4'

services:
  identitydb:
    container_name: identitydb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=IdentityDb
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  channelsdb:
    container_name: channelsdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  folks.apigateway:
    container_name: folks.apigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AuthenticationOptions__Authority=http://folks.identityservice.api"
    depends_on:
      - folks.identityservice.api
      - folks.channelsservice.api
    ports:
      - "8000:80"

  folks.channelsservice.api:
    container_name: folks.channelsservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "AuthenticationOptions__Authority=http://folks.identityservice.api"
      - "MongoDbConfig__ConnectionString=mongodb://channelsdb:27017"
      - "MongoDbConfig__DatabaseName=ChannelsDb"
      - "EventBusConfig__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - channelsdb
      - rabbitmq

  folks.identityservice.api:
    container_name: folks.identityservice.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__PostgreSqlConnectionString=Server=identitydb;Port=5432;Database=IdentityDb;User Id=admin;Password=admin1234;"
      - "EventBusConfig__HostAddress=amqp://guest:guest@rabbitmq:5672"
      - "IdentityServerConfig__IssuerUri=http://folks.identityservice.api"
    depends_on:
      - identitydb
      - rabbitmq
    ports:
      - "8001:80"
