version: '3.4'

name: folks
services:
  identitydb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  channelsdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  apigateway:
    image: ${APIGATEWAY_IMAGE_PATH}:${APIGATEWAY_TAG}
    build:
      context: .
      dockerfile: ApiGateways/Folks.ApiGateway/Dockerfile

  channels:
    image: ${CHANNELS_IMAGE_PATH}:${CHANNELS_TAG}
    build:
      context: .
      dockerfile: Services/Channels/Folks.ChannelsService.Api/Dockerfile

  identity:
    image: ${IDENTITY_IMAGE_PATH}:${IDENTITY_TAG}
    build:
      context: .
      dockerfile: Services/Identity/Folks.IdentityService.Api/Dockerfile

volumes:
  mongo_data:  
  postgres_data:
  pgadmin_data:

networks:
  default:
    name: folks
