version: '3.4'

services:
  identitydb:
    image: postgres

  chatdb:
    image: mongo

  pgadmin:
    image: dpage/pgadmin4 

  folks.apigateway:
    image: ${DOCKER_REGISTRY-}folksapigateway
    build:
      context: .
      dockerfile: ApiGateways/Folks.ApiGateway/Dockerfile

  folks.chatservice.api:
    image: ${DOCKER_REGISTRY-}folkschatserviceapi
    build:
      context: .
      dockerfile: Services/Chat/Folks.ChatService.Api/Dockerfile

  folks.identityservice.api:
    image: ${DOCKER_REGISTRY-}folksidentityserviceapi
    build:
      context: .
      dockerfile: Services/Identity/Folks.IdentityService.Api/Dockerfile

volumes:
  mongo_data:  
  postgres_data:
  pgadmin_data:
