version: '3.4'

services:
  identitydb:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    ports:
      - ${PGADMIN_EXTERNAL_PORT:-5050}:80
    volumes:
      - pgadmin_data:/root/.pgadmin

  channelsdb:
    restart: always
    ports:
      - ${CHANNELSDB_EXTERNAL_PORT:-27017}:27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    restart: always
    ports:
      - ${RABBITMQ_QUEUE_EXTERNAL_PORT:-5672}:5672
      - ${RABBITMQ_PLUGIN_EXTERNAL_PORT:-15672}:15672

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=${APIGATEWAY_ENVIRONMENT}
      - AuthenticationOptions__Authority=${AUTHORITY}
    depends_on:
      - identity
      - channels
    ports:
      - ${APIGATEWAY_EXTERNAL_PORT:-8000}:80

  channels:
    environment:
      - ASPNETCORE_ENVIRONMENT=${CHANNELS_ENVIRONMENT}
      - AuthenticationOptions__Authority=${AUTHORITY}
      - MongoDbConfig__ConnectionString=${CHANNELS_CONNECTION_STRING}
      - MongoDbConfig__DatabaseName=${CHANNELS_DATABASE_NAME}
      - EventBusConfig__HostAddress=${EVENT_BUS_HOSTADDRESS}
    depends_on:
      - channelsdb
      - rabbitmq

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=${IDENTITY_ENVIRONMENT}
      - ConnectionStrings__PostgreSqlConnectionString=${IDENTITY_CONNECTION_STRING}
      - EventBusConfig__HostAddress=${EVENT_BUS_HOSTADDRESS}
      - IdentityServerConfig__IssuerUri=${AUTHORITY}
    depends_on:
      - identitydb
      - rabbitmq
    ports:
      - ${IDENTITY_EXTERNAL_PORT:-8001}:80
