version: '3.4'

services:
  identitydb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  channelsdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  folks.apigateway:
    image: ${DOCKER_REGISTRY-}folksapigateway
    build:
      context: .
      dockerfile: ApiGateways/Folks.ApiGateway/Dockerfile

  folks.channelsservice.api:
    image: ${DOCKER_REGISTRY-}folkschannelsserviceapi
    build:
      context: .
      dockerfile: Services/Channels/Folks.ChannelsService.Api/Dockerfile

  folks.identityservice.api:
    image: ${DOCKER_REGISTRY-}folksidentityserviceapi
    build:
      context: .
      dockerfile: Services/Identity/Folks.IdentityService.Api/Dockerfile

volumes:
  mongo_data:  
  postgres_data:
  pgadmin_data:
