name: Channels Service CI (Dev)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Services/Channels/Folks.ChannelsService.Api/
    - name: Build
      run: dotnet build ./src/Services/Channels/Folks.ChannelsService.Api/ --no-restore
    - name: Run Application Unit Tests
      run: dotnet test ./src/Services/Channels/Tests/Folks.ChannelsService.Application.UnitTests/ --verbosity normal
    - name: Run Integration Tests
      run: dotnet test ./src/Services/Channels/Tests/Folks.ChannelsService.IntegrationTests/ --verbosity normal
